version: '3.8'
services:
  catalogo:
    build: ./fragmento_catalogo
    container_name: catalogo
    ports:
      - "5001:5000"

  ubicaciones_prestamos:
    build: ./fragmento_ubicaciones_prestamos
    container_name: ubicaciones_prestamos
    ports:
      - "5002:5000"

  interfaz_grafica:
    build: ./interfaz_grafica
    container_name: interfaz_grafica
    ports:
      - "5003:5000"
    depends_on:
      - catalogo
      - ubicaciones_prestamos
